### ISSUE TITLE
Add independence bivariate class

### ISSUE THREAD

**Issue by aliciasun** [DAI-Lab/Copulas#46]
### Description

Add a independence copula class to fit data that are not correlated.

**Comment by ManuelAlvarezC** [comment]
It's been implemented on the branch `46_independence_bivariate_copula`, however there are a couple implementation details I would like to make clear:

-  The `probability_density` implementation is based on the section `Other Comments` from [here](http://www.nematrian.com/IndependenceCopula).

- The `percent_point` (which is the reverse of the cumulative_distribution, that in the case of independence is the product) is not implemented as there are some ambiguity for which values should be returned, as for a given `y` in [0,1], there are multiple values `u`, `v`that fulfill `C(u,v) = y`. Such as:
```python 
C(1, y) = y
C(y, 1) = y
C(y ** 1 / 2, y ** 1 / 2) = y
C(x, y / x) = y  #  ( in this case for any x != 0)
```
Should we pick one option or leave it unimplemented?

What do you think @aliciasun @csala ?

**Comment by ManuelAlvarezC** [comment]
There was a misunderstanding in my last post.

The `percent_point` method in Bivariate copulas is not the inverse of `cumulative_distribution` but the inverse of `conditional_probability`, with that in mind, we can solve the question easily, because the `conditional_probability` of an independence copulas is the identity, and its inverse is also the identity.
