### ISSUE TITLE
python2 compatibility

### ISSUE THREAD

**Issue by benbrowne** [DAI-Lab/Copulas#60]
* Copulas version: 0.1.0
* Python version: 2.6
* Operating System:

### Description
Please could you explicitly inherit from `object` when declaring your base classes 'BVCopula', 'MVCopula', 'UnivariateDistrib' and others I may have missed. This should allow compatibility with python2. 
Many thanks!

### What I Did
The error when using python2 is ""TypeError: must be type, not classobj" whenever super is called.

I did some quick testing of parts of the codebase (not 100% coverage) to verify and explicitly inheriting from object does  seem to be the only limiting factor preventing python2 compatibility.

**Comment by ManuelAlvarezC** [comment]
HI brenbrowne, 

We decided to drop python 2 support because we had some compatibility issues and thought that it was not worth to fix them, given that our main dependencies will be dropping their support by the beginning of the next year.

However, we are open to any PR that adds support for python 2.7 back, but we won't add any specific changes to support 2.6. If you are interested in doing it, please, have a look at our Contributing Guide: https://github.com/DAI-Lab/Copulas/blob/master/CONTRIBUTING.rst
